- link: /notifications
  icon: apps/preferences-system-notifications
  title: Notifications
  has-submenu: false
  has-separator: false

- link: /search
  icon: apps/preferences-system-search
  title: Search
  has-submenu: false
  has-separator: false

- link: /system/datetime
  icon: apps/preferences-system-time
  title: Date & Time
  has-submenu: false
  has-separator: false

- link: /system/users
  icon: apps/system-users
  title: Users
  has-submenu: false
  has-separator: false

- link: /system/defaults
  icon: status/starred
  title: Default Applications
  has-submenu: false
  has-separator: false

- link: /system/ao
  icon: status/starred
  title: Default Applications
  has-submenu: false
  has-separator: false

- link: /system/about
  icon: actions/help-about
  title: About
  has-submenu: false
  has-separator: false
