- link: /network/wifi
  icon: devices/network-wireless
  title: Wi-Fi
  status: Connected

- link: /network/wired
  icon: devices/network-wired
  title: Wired
  status: Cable Unplugged

- link: /network/vpn
  icon: status/network-vpn
  title: VPN
  status: Not Set Up

- link: /network/proxy
  icon: apps/preferences-system-network-proxy
  title: Proxy
  status: Disabled

- link: /network/airplane-mode
  icon: status/airplane-mode
  title: Airplane Mode
  status: "Off"
